/**
 * P0 feasibility check for POSTERS-MULTI (board): does TMDB actually have
 * enough posters per title to make a multi-poster carousel worth building,
 * for *this* catalog (Arabic-heavy, many older titles) rather than TMDB's
 * catalog in general? Read-only research — never writes to the fixture,
 * never touches schema. `GET /movie/{id}/images` per title with a TMDB id,
 * through the same on-disk cache the other fixture scripts use.
 *
 *   cd apps/backend && npx tsx src/scripts/check-poster-multi-feasibility.ts
 */
import { config } from 'dotenv';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import path from 'node:path';

import { CACHE_DIR, cachedGet } from './wiki-http';
import { bucketFor, hasTmdbId, parsePosterCount, type CoverageBucket, type FeasibilityEntry } from './check-poster-multi-feasibility.lib';

config({ path: resolve(process.cwd(), '../../.env') });

const FIXTURE = path.resolve(__dirname, 'fixtures', 'catalog.demo.json');
const REPORT = path.resolve(__dirname, 'fixtures', 'catalog.demo.poster-multi-feasibility-report.md');
const GATE_THRESHOLD = 0.3;

async function main(): Promise<void> {
  const readToken = process.env.TMDB_READ_ACCESS_TOKEN;
  const apiKey = process.env.TMDB_API_KEY;
  if (!readToken && !apiKey) {
    console.error('TMDB_READ_ACCESS_TOKEN or TMDB_API_KEY is required (root .env)');
    process.exit(2);
  }

  const raw = JSON.parse(await readFile(FIXTURE, 'utf8')) as (FeasibilityEntry & Record<string, unknown>)[] | { entries: (FeasibilityEntry & Record<string, unknown>)[] };
  const entries = Array.isArray(raw) ? raw : raw.entries;
  console.log(`feasibility: ${entries.length} catalog entries; cache ${CACHE_DIR}`);

  const buckets: Record<CoverageBucket, string[]> = { no_tmdb_id: [], request_failed: [], zero: [], one: [], multi: [] };
  const counts = new Map<string, number | null>();

  for (const entry of entries) {
    if (!hasTmdbId(entry)) {
      buckets.no_tmdb_id.push(entry.internalId);
      continue;
    }
    const base = `https://api.themoviedb.org/3/movie/${encodeURIComponent(entry.externalIds!.tmdb!)}/images`;
    const url = readToken ? base : `${base}?api_key=${apiKey}`;
    const { status, body } = await cachedGet(url, readToken ? { Authorization: `Bearer ${readToken}` } : {});
    const count = parsePosterCount(status, body);
    counts.set(entry.internalId, count);
    buckets[bucketFor(count)].push(entry.internalId);
  }

  const total = entries.length;
  const multiCount = buckets.multi.length;
  const coverageOfCatalog = multiCount / total;
  const withTmdbId = total - buckets.no_tmdb_id.length;
  const coverageOfTmdbTitled = withTmdbId > 0 ? multiCount / withTmdbId : 0;
  const gatePasses = coverageOfCatalog >= GATE_THRESHOLD;

  const pct = (n: number) => `${(n * 100).toFixed(1)}%`;
  const lines = [
    '# POSTERS-MULTI — P0 TMDB feasibility check',
    '',
    `Generated by \`src/scripts/check-poster-multi-feasibility.ts\` on ${new Date().toISOString().slice(0, 10)}. Read-only: no write to \`catalog.demo.json\`, no schema change.`,
    '',
    '## Method',
    '',
    '`GET /movie/{id}/images` per title with a TMDB id, no `include_image_language` filter (confirmed live against this catalog and against a mainstream title that omitting the filter returns posters in every language TMDB has, not just the primary one). A title is "multi-poster-eligible" at 2+ posters returned. Cached on disk (`wiki-http.ts`), so a re-run is offline.',
    '',
    '## Gate (board POSTERS-MULTI, P0)',
    '',
    `Threshold: coverage < ~30% of the catalog → return to the owner, do not open P1. Measured: **${pct(coverageOfCatalog)}** of the ${total}-title catalog has 2+ TMDB posters → **${gatePasses ? 'PASSES the gate' : 'FAILS the gate'}**.`,
    '',
    '## Counts',
    '',
    `- Catalog entries: ${total}`,
    `- With a TMDB id: ${withTmdbId} (${pct(withTmdbId / total)}) · without one: ${buckets.no_tmdb_id.length}`,
    `- Request failed (404 or non-200 from TMDB): ${buckets.request_failed.length}`,
    `- 0 posters: ${buckets.zero.length} · exactly 1 poster: ${buckets.one.length} · 2+ posters (multi-eligible): ${multiCount}`,
    `- Coverage over the full catalog (${total}): **${pct(coverageOfCatalog)}**`,
    `- Coverage over titles with a TMDB id (${withTmdbId}): ${pct(coverageOfTmdbTitled)}`,
    '',
    '## Titles without a TMDB id (excluded from the numerator, counted in the denominator)',
    '',
    buckets.no_tmdb_id.length === 0 ? 'None.' : buckets.no_tmdb_id.join(', '),
    '',
    '## Titles with 0 or 1 poster (not multi-eligible)',
    '',
    `0 posters: ${buckets.zero.length ? buckets.zero.join(', ') : 'none'}`,
    '',
    `1 poster: ${buckets.one.length ? buckets.one.join(', ') : 'none'}`,
    '',
  ];
  await writeFile(REPORT, `${lines.join('\n')}\n`, 'utf8');
  console.log(`multi-eligible: ${multiCount}/${total} (${pct(coverageOfCatalog)}) → ${gatePasses ? 'PASS' : 'FAIL'} the 30% gate → ${path.basename(REPORT)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
