/**
 * Pure building blocks for staging director credits from Wikidata (blueprint
 * gap 6: `people`/`credits`/`source_records` exist since M3 but nothing has
 * ever populated them). No I/O, no TypeORM here -- `fetch-director-credits.ts`
 * does the HTTP calls and file writes; everything here is deterministic given
 * the raw Wikidata API responses, so the unit tests can pin it without a
 * network call.
 *
 * P57 ("director") is the only claim this reads: BP §7.1/§10.2 name director
 * as a person-effect block and BP §9.2 names it as a named diversity axis,
 * but nothing in this repository needs writer/cast credits yet, so those
 * aren't fetched -- adding them later is the same shape with a different
 * property id, not a redesign.
 */

// Minimal slice of the Wikidata wbgetentities response shape this needs --
// mirrors WdEntity/WdSnak in fetch-catalog.ts (that file exports neither, and
// this script is deliberately independent of it -- session C owns that file).
export interface WikidataSnak {
  mainsnak?: { datavalue?: { value?: unknown } };
}
export interface WikidataEntity {
  id: string;
  missing?: string;
  labels?: Record<string, { value: string }>;
  claims?: Record<string, WikidataSnak[]>;
}

export interface DirectorCredit {
  wikidataId: string;
  nameEn: string | null;
  nameAr: string | null;
  // Position in the P57 statement list as Wikidata returned it. Wikidata
  // doesn't guarantee this reflects any real-world ordering (no "series
  // ordinal" qualifier is read here) -- kept only as a stable, honest tie-
  // breaker, never presented as billing/importance order.
  creditOrder: number;
}

export interface TitleDirectorCredits {
  internalId: string;
  titleWikidataId: string;
  // Empty, not missing: a title can genuinely have no P57 claim on Wikidata
  // (absence is unknown, not a failure -- the same convention this codebase
  // uses for genres/fingerprint dimensions, BP §6/§11.3).
  directors: DirectorCredit[];
}

// The P57 ("director") claim's target is always a Wikidata item reference
// ({ "entity-type": "item", "id": "Q..." }); anything else on that property
// (a rare data-quality issue upstream) is skipped, not fabricated into one.
export function extractDirectorQids(entity: WikidataEntity): string[] {
  return (entity.claims?.P57 ?? [])
    .map((snak) => snak.mainsnak?.datavalue?.value)
    .filter((value): value is { id: string } => typeof value === 'object' && value !== null && 'id' in value)
    .map((value) => value.id);
}

function label(entity: WikidataEntity | undefined, lang: string): string | null {
  return entity?.labels?.[lang]?.value ?? null;
}

/**
 * Join each title's P57 director QIDs to the resolved person entities'
 * labels. `titleEntities`/`personEntities` are keyed by QID, exactly the
 * shape `wbgetentities` returns (batched fetches merge into one object
 * before this is called).
 */
export function buildDirectorCredits(
  titles: { internalId: string; wikidataId: string }[],
  titleEntities: Record<string, WikidataEntity>,
  personEntities: Record<string, WikidataEntity>,
): TitleDirectorCredits[] {
  return titles.map(({ internalId, wikidataId }) => {
    const titleEntity = titleEntities[wikidataId];
    const directorQids = titleEntity ? extractDirectorQids(titleEntity) : [];
    return {
      internalId,
      titleWikidataId: wikidataId,
      directors: directorQids.map((qid, index) => ({
        wikidataId: qid,
        nameEn: label(personEntities[qid], 'en'),
        nameAr: label(personEntities[qid], 'ar'),
        creditOrder: index,
      })),
    };
  });
}

export interface DirectorCreditsReportStats {
  totalTitles: number;
  titlesWithAtLeastOneDirector: number;
  titlesWithNoDirectorClaim: number;
  distinctDirectors: number;
  failures: { internalId: string; detail: string }[];
}

export function summarize(credits: TitleDirectorCredits[], failures: { internalId: string; detail: string }[]): DirectorCreditsReportStats {
  const distinctDirectors = new Set(credits.flatMap((entry) => entry.directors.map((director) => director.wikidataId)));
  return {
    totalTitles: credits.length + failures.length,
    titlesWithAtLeastOneDirector: credits.filter((entry) => entry.directors.length > 0).length,
    titlesWithNoDirectorClaim: credits.filter((entry) => entry.directors.length === 0).length,
    distinctDirectors: distinctDirectors.size,
    failures,
  };
}

export function renderReport(stats: DirectorCreditsReportStats, generatedAt: Date): string {
  const lines = [
    '# Demo catalog — director credits (blueprint gap 6)',
    '',
    `Generated by `.concat(
      '`apps/backend/src/scripts/fetch-director-credits.ts`',
      ` on ${generatedAt.toISOString().slice(0, 10)}.`,
    ),
    `Titles: ${stats.totalTitles} · with a director claim: ${stats.titlesWithAtLeastOneDirector} · no P57 claim on Wikidata: ${stats.titlesWithNoDirectorClaim} · fetch failed: ${stats.failures.length} · distinct directors resolved: ${stats.distinctDirectors}.`,
    '',
    'Staged output, not yet loaded: `catalog.demo.directors.json` keys credits by the fixture\'s own `internalId`, the same key `catalog.demo.json` uses, because no title has a database id yet (blueprint gap 6\'s ingestion pass runs before the catalog itself is loaded, WS3). Loading both into `titles`/`people`/`credits`/`source_records` is a separate, later step.',
  ];
  if (stats.failures.length > 0) {
    lines.push('', '## Failures', '', '| Id | Detail |', '|---|---|');
    for (const failure of stats.failures) {
      lines.push(`| ${failure.internalId} | ${failure.detail} |`);
    }
  }
  lines.push(
    '',
    '## Rules',
    '',
    '- Wikidata structured data is CC0 (DATA_LICENSING.md): P57 (director) claims and labels only, never writer/cast/crew -- nothing this codebase needs yet.',
    '- A title with no P57 claim on Wikidata is recorded with an empty `directors` array, not omitted and not a failure: absence is unknown, not zero (BP §6, §11.3), the same rule every fingerprint dimension already follows.',
    '- `creditOrder` is Wikidata\'s own statement order, not a billing/importance order -- no qualifier claims otherwise.',
  );
  return lines.join('\n') + '\n';
}
