/**
 * Poster path for the demo catalog, via the official TMDB API (board C-2,
 * archive B4) -- never scraping. One call per title with `externalIds.tmdb`
 * to `GET /movie/{id}`, through the same on-disk cache as the other fixture
 * fetches, so a re-run is offline and only new/forced titles cost a request.
 *
 *   cd apps/backend && npx tsx src/scripts/fetch-tmdb-posters.ts [--force] [--only DEMO0001,DEMO0002]
 *
 * Writes `entry.posterPath` on the fixture entry: TMDB's own relative path
 * (e.g. "/abc123.jpg"), or `null` when TMDB has none for that title -- never
 * a composed display URL (that belongs to whoever exposes it on
 * `PublicTitle`, gated by the current license environment, board M1) and
 * never the image itself. `load-catalog-rights.ts` writes the accompanying
 * `source_records` row for every title this leaves with a path.
 */
import { config } from 'dotenv';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import path from 'node:path';

import { CACHE_DIR, cachedGet } from './wiki-http';
import { needsPoster, parsePosterResponse, type PosterEntry } from './fetch-tmdb-posters.lib';

config({ path: resolve(process.cwd(), '../../.env') });

const DEFAULT_FIXTURE = path.resolve(__dirname, 'fixtures', 'catalog.demo.json');

function parseArgs(argv: string[]): { fixture: string; force: boolean; only: Set<string> | null } {
  const args = { fixture: DEFAULT_FIXTURE, force: false, only: null as Set<string> | null };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--fixture') {
      args.fixture = path.resolve(argv[++index]);
    } else if (arg === '--force') {
      args.force = true;
    } else if (arg === '--only') {
      args.only = new Set(argv[++index].split(',').map((value) => value.trim()).filter(Boolean));
    } else {
      throw new Error(`unknown argument ${arg}`);
    }
  }
  return args;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  // TMDB accepts a v4 read access token as a bearer header on the v3
  // endpoints, and that is the form to use (P1-1): a key in the query string
  // is a key in the cache filename, in this script's own error text, and in
  // any log between here and TMDB. The older v3 key has no header form at
  // all, so it still goes in the query -- with a warning, so nobody assumes
  // the credential is being kept out of URLs when it is not.
  const readToken = process.env.TMDB_READ_ACCESS_TOKEN;
  const apiKey = process.env.TMDB_API_KEY;
  if (!readToken && !apiKey) {
    console.error('TMDB_READ_ACCESS_TOKEN (preferred, sent as a header) or TMDB_API_KEY (v3, query string only) is required (root .env)');
    process.exit(2);
  }
  if (!readToken) {
    console.warn('note: using the v3 TMDB_API_KEY, which TMDB only accepts in the query string; a v4 TMDB_READ_ACCESS_TOKEN travels in a header instead');
  }

  const raw = JSON.parse(await readFile(args.fixture, 'utf8')) as (PosterEntry & Record<string, unknown>)[] | { entries: (PosterEntry & Record<string, unknown>)[] };
  const entries = Array.isArray(raw) ? raw : raw.entries;
  const candidates = entries.filter((entry) => (!args.only || args.only.has(entry.internalId)) && needsPoster(entry, args.force));
  console.log(`posters: ${entries.length} entries in ${path.basename(args.fixture)}; ${candidates.length} need a poster path; cache ${CACHE_DIR}`);

  let found = 0;
  let none = 0;
  for (const entry of candidates) {
    const base = `https://api.themoviedb.org/3/movie/${encodeURIComponent(entry.externalIds!.tmdb!)}`;
    const url = readToken ? base : `${base}?api_key=${apiKey}`;
    const { status, body } = await cachedGet(url, readToken ? { Authorization: `Bearer ${readToken}` } : {});
    entry.posterPath = parsePosterResponse(status, body);
    if (entry.posterPath) {
      found += 1;
    } else {
      none += 1;
    }
  }

  const output = Array.isArray(raw) ? entries : { ...raw, entries };
  await writeFile(args.fixture, `${JSON.stringify(output, null, 2)}\n`, 'utf8');

  const withoutTmdb = entries.filter((entry) => !entry.externalIds?.tmdb).length;
  const withPoster = entries.filter((entry) => typeof entry.posterPath === 'string').length;
  const reportPath = args.fixture.replace(/\.json$/, '.posters-report.md');
  await writeFile(
    reportPath,
    [
      '# Demo catalog — TMDB poster paths',
      '',
      `Generated by \`src/scripts/fetch-tmdb-posters.ts\` on ${new Date().toISOString().slice(0, 10)} (TMDB API, never scraping).`,
      `Entries: ${entries.length} · with a TMDB id: ${entries.length - withoutTmdb} · fetched this run: ${candidates.length} (${found} with a poster, ${none} without) · with a poster path overall: ${withPoster} · no TMDB id at all: ${withoutTmdb}.`,
      '',
      '## Rules',
      '',
      '- `posterPath` is TMDB\'s own relative path, never a composed URL and never the image bytes.',
      '- No poster path is invented: a 404 or a null `poster_path` from TMDB is stored as `null`, not retried as a failure.',
      '- Attribution and license status are recorded once per title by `load-catalog-rights.ts` (`fieldName: posterPath`, `source: tmdb`, `non_commercial_only`).',
      '',
      withoutTmdb === 0
        ? 'Every title has a TMDB id.'
        : `Titles with no TMDB id (${withoutTmdb}): ${entries.filter((entry) => !entry.externalIds?.tmdb).map((entry) => entry.internalId).join(', ')}`,
      '',
    ].join('\n'),
    'utf8',
  );
  console.log(`  ${found} fetched with a poster, ${none} fetched with none, ${withPoster} total with a path → ${path.basename(reportPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
