/**
 * PUB-S1 (ADR-118) shadow report: runs the `public-v1` evaluator over the
 * live catalog and prints/saves the readiness counts the coordinator asked
 * for before authorizing PUB-B1. Read-only -- every query is a `.find()`;
 * nothing here writes `title_revisions`, sets `titles.publishedRevisionId`,
 * or touches any other table. Same code path as `GET
 * /admin/publication/readiness` (`PublicationPreviewService.shadowReport()`),
 * just called directly against a DataSource instead of through the HTTP app.
 *
 *   cd apps/backend && npx tsx src/scripts/publication-readiness-shadow-report.ts
 */
import 'reflect-metadata';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { DataSource, DataSourceOptions } from 'typeorm';
import { DatabaseConfig } from '../config/database.config';
import { SourceRecord } from '../entities/source-record.entity';
import { Title } from '../entities/title.entity';
import { PublicationPolicyService, PublicationBlockerCode } from '../modules/publication/publication-policy.service';
import { PublicationPreviewService } from '../modules/publication/publication-preview.service';

const REPORT = path.resolve(__dirname, 'publication-readiness-shadow-report.md');

const BLOCKER_ORDER: PublicationBlockerCode[] = [
  'POSTER_MISSING',
  'DESCRIPTION_MISSING',
  'GENRES_MISSING',
  'IDENTITY_UNRESOLVED',
  'LICENSE_BLOCKED',
];

async function main(): Promise<void> {
  const dataSource = new DataSource(DatabaseConfig() as DataSourceOptions);
  await dataSource.initialize();

  try {
    const preview = new PublicationPreviewService(
      dataSource.getRepository(Title),
      dataSource.getRepository(SourceRecord),
      new PublicationPolicyService(),
    );
    const report = await preview.shadowReport();
    const titlesByInternalId = new Map((await dataSource.getRepository(Title).find()).map((t) => [t.id, t.internalId]));

    const pct = (n: number) => `${((n / report.totalTitles) * 100).toFixed(1)}%`;
    const notReady = report.titles.filter((t) => !t.ready);

    console.log(`public-v1 shadow report: ${report.totalTitles} titles, ${report.readyCount} ready (${pct(report.readyCount)}), ${notReady.length} blocked`);
    for (const code of BLOCKER_ORDER) {
      console.log(`  ${code}: ${report.blockerCounts[code] ?? 0}`);
    }

    const lines = [
      '# PUB-S1 — public-v1 shadow report (read-only)',
      '',
      `Generated by \`src/scripts/publication-readiness-shadow-report.ts\` on ${new Date().toISOString().slice(0, 10)}, policy \`${report.policyVersion}\`. Read-only: no write to \`title_revisions\` or \`titles.publishedRevisionId\`.`,
      '',
      '## Counts',
      '',
      `- Total titles: ${report.totalTitles}`,
      `- Ready (zero blockerCodes): ${report.readyCount} (${pct(report.readyCount)})`,
      `- Blocked (1+ blockerCodes): ${notReady.length} (${pct(notReady.length)})`,
      '',
      '## Blocker code distribution (a blocked title may carry more than one)',
      '',
      ...BLOCKER_ORDER.map((code) => `- ${code}: ${report.blockerCounts[code] ?? 0}`),
      '',
      '## Blocked titles',
      '',
      notReady.length === 0
        ? 'None.'
        : notReady
            .map((t) => `- ${titlesByInternalId.get(t.titleId) ?? t.titleId}: ${t.blockerCodes.join(', ')}`)
            .join('\n'),
      '',
    ];
    await writeFile(REPORT, `${lines.join('\n')}\n`, 'utf8');
    console.log(`saved -> ${path.basename(REPORT)}`);
  } finally {
    await dataSource.destroy();
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
